# Data Frames
Combining multiple Series

In [99]:
import numpy as np
import pandas as pd

### Creating a DataFrame

In [100]:
data = {
  'Name' : ['Alice', 'Bob', 'Charlie', 'David'],
  'Age' : [25, 30, 35, 40],
  'City' : ['New York', 'Los Angeles', 'Chicago', 'Houston'],
  'Salary' : [70000, 80000, 90000, 100000]
}

df = pd.DataFrame(data)

In [101]:
df

      Name  Age         City  Salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000
3    David   40      Houston  100000

In [102]:
data_list = [
  ['Alice', 25, 'New York',70000],
  ['Bob', 30, 'Los Angeles', 80000],
  ['Charlie', 35, 'Chicago', 90000],
  ['David', 40, 'Houston', 100000]
]

In [103]:
df2 = pd.DataFrame(data_list)
df2

         0   1            2       3
0    Alice  25     New York   70000
1      Bob  30  Los Angeles   80000
2  Charlie  35      Chicago   90000
3    David  40      Houston  100000

In [104]:
columns = [ "Name" , "Age" , "City" , "Salary"]
df2 = pd.DataFrame(data_list , columns = columns)
df2

      Name  Age         City  Salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000
3    David   40      Houston  100000

### Selection and Indexing of Columns

In [105]:
df2
# I want to select the name column

      Name  Age         City  Salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000
3    David   40      Houston  100000

In [106]:
df2['Name']

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: str

In [107]:
# we want to target two columns
df2['Age']

0    25
1    30
2    35
3    40
Name: Age, dtype: int64

In [108]:
df2[["Name" , "Salary"]]  # list of list to target multiple columns

      Name  Salary
0    Alice   70000
1      Bob   80000
2  Charlie   90000
3    David  100000

### Creating a new column

In [109]:
df2["Designation"] = ["Doctor" , "Engineer" , "Plumber" , "Star"] #len(df2["Designation"]) == no. of rows excluding header pr column name

In [110]:
df2

      Name  Age         City  Salary Designation
0    Alice   25     New York   70000      Doctor
1      Bob   30  Los Angeles   80000    Engineer
2  Charlie   35      Chicago   90000     Plumber
3    David   40      Houston  100000        Star

### Removing Columns

In [111]:
df2.drop("Designation" ,axis = 1)  #drop will remove row as default axis = 0
## This is jus a shallow copy not the actual dataframe

      Name  Age         City  Salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000
3    David   40      Houston  100000

In [112]:
df2  # Designation is not removed from main database

      Name  Age         City  Salary Designation
0    Alice   25     New York   70000      Doctor
1      Bob   30  Los Angeles   80000    Engineer
2  Charlie   35      Chicago   90000     Plumber
3    David   40      Houston  100000        Star

In [113]:
df2.drop("Designation" , axis = 1, inplace = True)

In [114]:
df2

      Name  Age         City  Salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000
3    David   40      Houston  100000

In [115]:
df2.drop(["City", "Salary"] , axis = 1 ,)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

In [116]:
df2

      Name  Age         City  Salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000
3    David   40      Houston  100000

In [117]:
df2.drop(0 , axis = 0)

      Name  Age         City  Salary
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000
3    David   40      Houston  100000

In [118]:
df2.drop([0,2,3] , axis = 0)

  Name  Age         City  Salary
1  Bob   30  Los Angeles   80000

### Selecting Rows

In [119]:
df2

      Name  Age         City  Salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000
3    David   40      Houston  100000

In [120]:
df2.loc[0]

Name         Alice
Age             25
City      New York
Salary       70000
Name: 0, dtype: object

In [121]:
df2.loc[[0]]

    Name  Age      City  Salary
0  Alice   25  New York   70000

In [122]:
df2.loc[[0,2]]  #This is using row labels

      Name  Age      City  Salary
0    Alice   25  New York   70000
2  Charlie   35   Chicago   90000

In [123]:
## This is for row indexing
df2.iloc[3]

Name        David
Age            40
City      Houston
Salary     100000
Name: 3, dtype: object

### Selecting subset of rows and column

In [124]:
df

      Name  Age         City  Salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000
3    David   40      Houston  100000

In [125]:
df.loc[[0,1]][["City" , "Salary"]]

          City  Salary
0     New York   70000
1  Los Angeles   80000

In [126]:
df.loc[[2,3]][["Name" , "Age"]]

      Name  Age
2  Charlie   35
3    David   40

### Conditinal Selection

In [127]:
df2

      Name  Age         City  Salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000
3    David   40      Houston  100000

In [130]:
# Age above 30

df2[df2["Age"] >  30]

      Name  Age     City  Salary
2  Charlie   35  Chicago   90000
3    David   40  Houston  100000

In [132]:
# Agw above 30 and city is Chicago

df2[(df2["Age"] > 30) &  (df2["City"] == "Chicago")]

      Name  Age     City  Salary
2  Charlie   35  Chicago   90000