In [6]:
import numpy as np
import pandas as pd

### Finding Missing Data

In [13]:
data = {
  'A': [1 , 2 , np.nan ,4 , 5 ],
  'B': [np.nan , 2, 3, 4, 5],
  'C': [1 ,2 ,3 , np.nan , np.nan],
  'D': [1 , np.nan , np.nan , np.nan , 5]
}
# np.nan is not a number(nan)
df = pd.DataFrame(data)

In [14]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [ ]:
df.isna()  #Gives False for NA values such as None , and np.NaN. It doe snot consider "" , np.if

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
# Find number of Null values
df.isna().sum()  # Use ful for Large DataSets

A    1
B    1
C    2
D    3
dtype: int64

In [21]:
# To check whether null value exist
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

### Removing Missing Data

In [22]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [23]:
df.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [27]:
df.loc[0 ,'B'] = 1
df

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [28]:
df.dropna()

     A    B    C    D
0  1.0  1.0  1.0  1.0

In [29]:
df

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [31]:
df.dropna(thresh = 3)   ## Checks for a threshold of N non null values (thres = N)

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

In [32]:
df.dropna(thresh = 4)

     A    B    C    D
0  1.0  1.0  1.0  1.0

In [34]:
df.dropna(thresh = 5)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

### Filling the missing Data

In [35]:
df

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [ ]:
df.fillna(0)  ## Column wise

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [38]:
values = { 'A':0 , 'B': 100 , 'C' : 300 , 'D' : 400}
df.fillna(value = values)  # inplace = True to change the df

     A    B      C      D
0  1.0  1.0    1.0    1.0
1  2.0  2.0    2.0  400.0
2  0.0  3.0    3.0  400.0
3  4.0  4.0  300.0  400.0
4  5.0  5.0  300.0    5.0

In [41]:
df

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [40]:
## To fill mean values in place of null value

df.fillna(df.mean())

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0